"use client"
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
// import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import useToggle from "@/hooks/useToggle";
import './global.css'
// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
//   };

  const urbanist = Urbanist({
    subsets: ["latin"],
    weight: ["400", "500", "700"], // Specify the weights you need
  });
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    const [isOpen, toggle] = useToggle(false)
    return (
      <div className={`${urbanist.className} antialiased`}>
        <div className="flex antialiased">
          <Sidebar isOpen={isOpen} toggle={toggle}/>

          <div className="flex-1">
            <Topbar toggle={toggle}/>
            <div className='lg:w-[92%] p-2 mx-auto'>{children}</div>
          </div>
        </div>
      </div>
    );
  }
  